# Generated by Django 5.1.3 on 2025-01-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroom',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
    ]
