# Generated by Django 5.1.3 on 2025-01-02 04:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userroom_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroom',
            unique_together={('user',)},
        ),
    ]
