# Generated by Django 5.1.4 on 2025-01-02 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userroom_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroom',
            unique_together={('user', 'room')},
        ),
    ]
