# Generated by Django 5.1.4 on 2025-01-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
