# Generated by Django 5.1.4 on 2025-01-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_room_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status_evaluated_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='status_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
