# Generated by Django 5.1.4 on 2025-01-28 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_room_status_evaluated_time_room_status_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroom',
            unique_together={('user', 'room', 'status')},
        ),
    ]
