# Generated by Django 5.1.4 on 2025-01-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userroom_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroom',
            unique_together=set(),
        ),
    ]
